name: Docker
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  REPOSITORY: ndfeb/testing

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # This is what we are going to use to run the next job in our new image
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REPOSITORY }}
          tags: type=sha,prefix=

      - run: echo "steps.meta.outputs.tags = ${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ needs.build.outputs.image_tag }}
    steps:
      - name: Does this look like your image?
        run: ls -l /

      - name: Assert that our test file is here
        run: test "$(cat /test.txt)" == "Do I exist?"
